image:
  repository: shoppingcartdevopsdemo.azurecr.io/shopping-cart-devops-demo/cart
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

securityContext:
  readOnlyRootFilesystem: true
  # runAsNonRoot: true

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  host: shopping-cart-devops-demo.lesne.pro
  tls: {}

resources:
  limits:
    cpu: 300m
    memory: 300Mi
  requests:
    cpu: 200m
    memory: 200Mi

azure:
  tenantId: 0dbe2ab8-25ae-40a9-be67-b9afd61f7068

databases:
  cosmosdb:
    uri: https://shopping-cart-devops-demo.documents.azure.com:443/
  redis:
    host: shopping-cart-devops-demo.redis.cache.windows.net
    port: 6380
    username: ""
    db: 0

autoscaling:
  minReplicas: 1
  maxReplicas: 100
  # applicationInsightsId: a2959c16-db50-4f56-a280-c110d1848306

secrets:
  keyvaultName: shoppingcartdevopsdemo
  userAssignedClientId: 933a70e7-4238-448a-96f4-5651c3516f7c
  serviceAccountName: workload-identity-sa

# Default affinity target amd64 nodes only as the image is not multi-arch.
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/arch
              operator: In
              values:
                - amd64
