replicaCount: 2

image:
  repository: shoppingcartdevopsdemo.azurecr.io/cart
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

securityContext:
  readOnlyRootFilesystem: true
  # runAsNonRoot: true

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  host: shopping-cart-devops-demo.westeurope.cloudapp.azure.com
  tls: {}

resources:
  limits:
    cpu: 200m
    memory: 200Mi
  requests:
    cpu: 200m
    memory: 200Mi

azure:
  tenantId: 0dbe2ab8-25ae-40a9-be67-b9afd61f7068

autoscaling:
  minReplicas: 1
  maxReplicas: 100
  # applicationInsightsId: a2959c16-db50-4f56-a280-c110d1848306

secrets:
  keyvaultName: shoppingcartdevopsdemo
  userAssignedClientId: 933a70e7-4238-448a-96f4-5651c3516f7c
  serviceAccountName: workload-identity-sa
