trigger:
  - master
  - develop
  - feat/*
  - hotfix/*

pool: Azure Pipelines

variables:
  branch_raw: ${{ replace(variables['Build.SourceBranch'], 'refs/heads/', '') }}
  branch_sanitized: ${{ replace(replace(variables.branch_raw, '/', '-'), '_', '-') }}

stages:
  - template: cicd/pipelines/init.yaml

  - template: cicd/pipelines/integration.yaml

  - ${{ if or(contains(variables.branch_raw, 'develop'), contains(variables.branch_raw, 'feat/'), contains(variables.branch_raw, 'hotfix/')) }}:
    - template: cicd/pipelines/deploy.yaml
      parameters:
        depends: integration
        env : dev
        instance: ${{ variables.branch_sanitized }}

    - template: cicd/pipelines/test-integration.yaml
      parameters:
        depends: deploy_dev_${{ replace(variables.branch_sanitized, '-', '_') }}
        env : dev
        instance: ${{ variables.branch_sanitized }}

  - ${{ if eq(variables.branch_raw, 'master') }}:
      - template: cicd/pipelines/deploy.yaml
        parameters:
          depends: integration
          env : preprod
          instance: ${{ variables.branch_sanitized }}

      - template: cicd/pipelines/deploy.yaml
        parameters:
          depends: deploy_preprod_${{ replace(variables.branch_sanitized, '-', '_') }}
          env : prod
          instance: ${{ variables.branch_sanitized }}
