# Use the shared agent pool
pool: Azure Pipelines

# Trigger run on any version tag and on "develop", "feat/*", "hotfix/*" and "master" branches
trigger:
  tags:
    include:
      - v*
  branches:
    include:
      - develop
      - feat/*
      - hotfix/*
      - master

# Schedule run on "master" and "develop" every monday at 00:00
schedules:
  - cron: "0 0 * * 1"
    displayName: Weekly build
    always: true
    branches:
      include:
        - develop
        - master

variables:
  - group: shopping-cart-devops-demo
  - name: branch_raw
    value: ${{ replace(variables['Build.SourceBranch'], 'refs/heads/', '') }}
  - name: branch_sanitized
    value: ${{ replace(replace(variables.branch_raw, '/', '-'), '_', '-') }}

stages:
  - template: cicd/pipelines/stage-build.yaml

  - ${{ if or(contains(variables.branch_raw, 'develop'), contains(variables.branch_raw, 'feat/'), contains(variables.branch_raw, 'hotfix/')) }}:
    - template: cicd/pipelines/stage-env.yaml
      parameters:
        branch_sanitized: ${{ variables.branch_sanitized }}
        dependencytrack_secret: $(dependencytrack_secret)
        env: dev
        teams_webhook: $(teams_webhook)

  - ${{ if eq(variables.branch_raw, 'master') }}:
    - template: cicd/pipelines/stage-env.yaml
      parameters:
        branch_sanitized: ${{ variables.branch_sanitized }}
        dependencytrack_secret: $(dependencytrack_secret)
        env: preprod
        teams_webhook: $(teams_webhook)

    - template: cicd/pipelines/stage-env.yaml
      parameters:
        branch_sanitized: ${{ variables.branch_sanitized }}
        dependencytrack_secret: $(dependencytrack_secret)
        env: prod
        teams_webhook: $(teams_webhook)
