stages:
  - stage: init
    displayName: Initialize
    jobs:
      - job: default
        displayName: Default
        steps:
          - checkout: self
            displayName: Checkout sources
            fetchDepth: 0
            fetchTags: true

          - bash: |
              version_full=$(make version-full)
              echo "##vso[task.setvariable variable=version;isOutput=true]$version_full"
            displayName: Set pipeline name
