parameters:
  - name: depends
  - name: env
  - name: instance
  - name: teams_webhook

stages:
  - stage: rollback_${{ parameters.env }}_${{ replace(parameters.instance, '-', '_') }}
    displayName: Rollback ${{ parameters.env }} for ${{ parameters.instance }}
    condition: failed()
    dependsOn: ${{ parameters.depends }}
    lockBehavior: sequential
    jobs:
      - job: cart
        displayName: Cart service
        steps:
          - checkout: self
            displayName: Checkout sources
            fetchDepth: 0
            fetchTags: true
            submodules: true

          - template: step-setup-kubectl.yaml

          - task: AzureCLI@2
            displayName: Deploy instance
            env:
              # Connect to Azure DevOps Artifacts
              AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
            inputs:
              azureSubscription: azure-shopping-cart-devops-demo
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                # Connect to Azure Kubernetes Service
                az aks get-credentials --resource-group shopping-cart-devops-demo --name shoppingcartdevopsdemo
                kubelogin convert-kubeconfig -l azurecli

                # Exec our build
                make --directory ./src/cart env=${{ parameters.env }} instance=${{ parameters.instance }} rollback

          - template: step-send-notification.yaml
            parameters:
              title: Instance "${{ parameters.instance }}" in "${{ parameters.env }}" is rollbacked
              description: $(Build.SourceVersionMessage)
              teams_webhook: ${{ parameters.teams_webhook }}

          - template: step-add-tag.yaml
            parameters:
              tag: rollback-${{ parameters.env }}
