parameters:
  - name: depends
  - name: env
  - name: instance
  - name: teams_webhook

stages:
  - stage: rollback_${{ parameters.env }}_${{ replace(parameters.instance, '-', '_') }}
    displayName: Rollback ${{ parameters.env }} for ${{ parameters.instance }}
    condition: failed()
    dependsOn: ${{ parameters.depends }}
    lockBehavior: sequential
    jobs:
      - job: cart
        displayName: Cart service
        steps:
          - template: step-checkout.yaml

          - template: step-setup-kubectl.yaml

          - task: HelmDeploy@0
            displayName: Helm rollback
            inputs:
              azureResourceGroup: shopping-cart-devops-demo
              azureSubscriptionEndpoint: azure-shopping-cart-devops-demo
              command: rollback
              kubernetesCluster: shoppingcartdevopsdemo
              namespace: ${{ parameters.env }}
              releaseName: ${{ parameters.instance }}
              waitForExecution: true

          - template: step-send-notification.yaml
            parameters:
              title: Instance "${{ parameters.instance }}" in "${{ parameters.env }}" is rollbacked
              description: $(Build.SourceVersionMessage)
              teams_webhook: ${{ parameters.teams_webhook }}

          - template: step-add-tag.yaml
            parameters:
              tag: rollback-${{ parameters.env }}
