parameters:
  - name: dependencytrack_secret
  - name: depends
  - name: env
  - name: instance
  - name: teams_webhook

stages:
  - stage: deploy_${{ parameters.env }}_${{ replace(parameters.instance, '-', '_') }}
    displayName: Deploy ${{ parameters.env }} for ${{ parameters.instance }}
    condition: succeeded()
    dependsOn: ${{ parameters.depends }}
    lockBehavior: sequential
    jobs:
      - job: cart
        displayName: Cart service
        pool:
          name: onprem_aks
          demands:
            # Azure CLI DevOps extension is bugged on ARM64 (https://github.com/Azure/azure-devops-cli-extension/issues/1006)
            - arch_x64
        steps:
          - template: step-checkout.yaml

          - template: step-add-tag.yaml
            parameters:
              tag: instance-${{ parameters.instance }}

          - template: step-setup-kubectl.yaml

          - template: step-publish-sbom.yaml
            parameters:
              dependencytrack_secret: ${{ parameters.dependencytrack_secret }}
              env: ${{ parameters.env }}
              instance: ${{ parameters.instance }}
              package: cart-app-sbom

          - template: step-publish-sbom.yaml
            parameters:
              dependencytrack_secret: ${{ parameters.dependencytrack_secret }}
              env: ${{ parameters.env }}
              instance: ${{ parameters.instance }}
              package: cart-container-sbom

          - bash: |
              az config set extension.use_dynamic_install=yes_without_prompt

              az artifacts universal download \
                  --feed shopping-cart-devops-demo \
                  --name cart-helm \
                  --organization https://dev.azure.com/$(System.TeamProject) \
                  --path $(Build.ArtifactStagingDirectory) \
                  --version $(version)
            displayName: Helm download
            env:
              AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)

          - task: AzureCLI@2
            displayName: Helm upgrade
            env:
              AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
            inputs:
              azureSubscription: azure-shopping-cart-devops-demo
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                # Connect to Azure Kubernetes Service
                az aks get-credentials --resource-group shopping-cart-devops-demo --name shoppingcartdevopsdemo
                kubelogin convert-kubeconfig -l azurecli

                # Exec our deploy
                helm upgrade --install \
                    --atomic \
                    --namespace ${{ parameters.env }} \
                    ${{ parameters.instance }} \
                    $(Build.ArtifactStagingDirectory)/cart-$(version).tgz

          - template: step-send-notification.yaml
            parameters:
              title: Instance "${{ parameters.instance }}" in "${{ parameters.env }}" is deployed
              description: $(Build.SourceVersionMessage)
              teams_webhook: ${{ parameters.teams_webhook }}

          - template: step-add-tag.yaml
            parameters:
              tag: deploy-${{ parameters.env }}
