parameters:
  - name: dependencytrack_secret
  - name: depends
  - name: env
  - name: instance
  - name: teams_webhook

stages:
  - stage: deploy_${{ parameters.env }}_${{ replace(parameters.instance, '-', '_') }}
    displayName: Deploy ${{ parameters.env }} for ${{ parameters.instance }}
    condition: succeeded()
    dependsOn: ${{ parameters.depends }}
    lockBehavior: sequential
    jobs:
      - job: cart
        displayName: Cart service
        steps:
          - checkout: self
            displayName: Checkout sources
            fetchDepth: 0
            fetchTags: true
            submodules: true

          - template: step-add-tag.yaml
            parameters:
              tag: instance-${{ parameters.instance }}

          - task: AzureCLI@2
            displayName: Publish tests
            env:
              AZURE_DEVOPS_EXT_PAT: $(System.AccessToken) # Connect to Azure Artifacts
            inputs:
              azureSubscription: azure-shopping-cart-devops-demo
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                make --directory ./src/cart dependencytrack_secret=${{ parameters.dependencytrack_secret }} env=${{ parameters.env }} instance=${{ parameters.instance }} publish-tests

          # Do not trust the build steps: always re-test the binaries security
          # - template: step-cart-container-cve.yaml

          - template: step-setup-kubectl.yaml

          - task: AzureCLI@2
            displayName: Deploy instance
            env:
              AZURE_DEVOPS_EXT_PAT: $(System.AccessToken) # Connect to Azure Artifacts
            inputs:
              azureSubscription: azure-shopping-cart-devops-demo
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                # Connect to Azure Kubernetes Service
                az aks get-credentials --resource-group shopping-cart-devops-demo --name shoppingcartdevopsdemo
                kubelogin convert-kubeconfig -l azurecli

                # Exec our build
                make --directory ./src/cart env=${{ parameters.env }} instance=${{ parameters.instance }} deploy

          - template: step-send-notification.yaml
            parameters:
              title: Instance "${{ parameters.instance }}" in "${{ parameters.env }}" is deployed
              description: $(Build.SourceVersionMessage)
              teams_webhook: ${{ parameters.teams_webhook }}

          - template: step-add-tag.yaml
            parameters:
              tag: deploy-${{ parameters.env }}
